package _12_exceptions._08_finally._01_to_do_what;

/**
 * @Author wx-li
 * @Date 2019/8/30 10:12
 **/

class FourException extends Exception {}

public class AlawaysFinally {
    public static void main(String[] args) {
        System.out.println("Entering first try block");
        try {
            System.out.println("Entering second try block");
            try {
                throw new FourException();
            } finally {
                System.out.println("finally in 2nd try block");
            }
        } catch (FourException e) {
            System.out.println("Caught FourException in 1st try block");
        } finally {
            System.out.println("finally in 1st try block");
        }
    }
}
